# Generated by Django 4.2.7 on 2023-11-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0004_course_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.RemoveField(
            model_name='student',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='created_user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='isactive',
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Photo'),
        ),
    ]
