# Generated by Django 4.2.6 on 2023-11-24 10:11

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0005_alter_student_options_remove_student_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='district',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='state', chained_model_field='state', on_delete=django.db.models.deletion.CASCADE, to='demo_app.district'),
        ),
        migrations.AlterField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_app.state'),
        ),
        migrations.AlterField(
            model_name='state',
            name='statename',
            field=models.CharField(max_length=200, unique=True, verbose_name='State'),
        ),
    ]
